# Generated by Django 3.2.13 on 2022-06-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=150, verbose_name='Source Name')),
                ('author', models.CharField(blank=True, max_length=150, null=True, verbose_name='Author')),
                ('haeadline', models.TextField(blank=True, null=True)),
                ('news_source', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('country_of_news', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country of News')),
                ('published_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'News Info',
                'db_table': 'news_info',
                'ordering': ['-published_at'],
                'managed': True,
            },
        ),
    ]
