# Generated by Django 3.2.13 on 2022-06-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeedapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsfeedSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, null=True)),
                ('news_source', models.TextField(blank=True, null=True)),
                ('news_keyword', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'News Settings ',
                'db_table': 'newsfeed_settings',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
    ]
